// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeJgGqqkwiMiSSMb07XgcIKPohPt5THzs',
    appId: '1:419935515316:web:644ed7b2147f865a0bdde1',
    messagingSenderId: '419935515316',
    projectId: 'eduhire-e7015',
    authDomain: 'eduhire-e7015.firebaseapp.com',
    storageBucket: 'eduhire-e7015.firebasestorage.app',
    measurementId: 'G-7P2X0GP3WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbz34wKwu5PC5gQnZfm7YzGfdN1a93usI',
    appId: '1:419935515316:android:6f59a91196032bbf0bdde1',
    messagingSenderId: '419935515316',
    projectId: 'eduhire-e7015',
    storageBucket: 'eduhire-e7015.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6DNxP2crzUscXX1HOHzBn1ozJtOxFOks',
    appId: '1:419935515316:ios:5eba4cc3a7fa65d80bdde1',
    messagingSenderId: '419935515316',
    projectId: 'eduhire-e7015',
    storageBucket: 'eduhire-e7015.firebasestorage.app',
    iosClientId: '419935515316-7h3qmd09dd1s9678i9ettvmahol3uhk0.apps.googleusercontent.com',
    iosBundleId: 'com.aitech.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6DNxP2crzUscXX1HOHzBn1ozJtOxFOks',
    appId: '1:419935515316:ios:5eba4cc3a7fa65d80bdde1',
    messagingSenderId: '419935515316',
    projectId: 'eduhire-e7015',
    storageBucket: 'eduhire-e7015.firebasestorage.app',
    iosClientId: '419935515316-7h3qmd09dd1s9678i9ettvmahol3uhk0.apps.googleusercontent.com',
    iosBundleId: 'com.aitech.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeJgGqqkwiMiSSMb07XgcIKPohPt5THzs',
    appId: '1:419935515316:web:2bd26fd0bfb9961c0bdde1',
    messagingSenderId: '419935515316',
    projectId: 'eduhire-e7015',
    authDomain: 'eduhire-e7015.firebaseapp.com',
    storageBucket: 'eduhire-e7015.firebasestorage.app',
    measurementId: 'G-HK6FX0NEM4',
  );
}
